config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :articles
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories
  has_many :categories, through: :article_categories
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article 
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name,
            presence: true,
            length: { minimum: 3, maximum: 25 },
            uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  has_many :articles, dependent: :destroy
  validates :username, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: { case_sensitive: false }

  VALID_EMAIL_REGEX = /\A[a-z0-9\+\-_\.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  
  private 
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:warning] = "Please login first"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was succesfully updated"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:success] = 'Article was successfully deleted.'
    redirect_to articles_url
  end
  
  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def correct_user
      unless current_user == @article.user || current_user.admin?
        flash[:warning] = "You can only edit or delete your own article unless you are an admin"
        redirect_to @article
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :admin_only, except: [:index, :show]
  before_action :set_category, only: [:edit, :update, :show]
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category name successfully updated"
      redirect_to @category
    else
      render 'edit'
    end
  end
  
  private
    def category_params
      params.require(:category).permit(:name)
    end

    def admin_only
      unless (logged_in? && current_user.admin)
        flash[:warning] = "Only admins can perform that action"
        redirect_to categories_path
      end
    end

    def set_category
      @category = Category.find(params[:id])
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:warning] = "Invalid login credentials"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}. You have successfully signed up."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account information was successfully updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    redirect_to root_path
    flash[:danger] = "Account deleted permanently."
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
   
    def set_user
      @user = User.find(params[:id])
    end

    def correct_user
      unless current_user == @user || current_user.admin?
        flash[:warning] = "You can only edit or delete your own profile"
        redirect_to current_user
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row">
      <div class="col-8 offset-sm-2 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= link_to article.user.username, article.user if article.user.present? %>
            <div class="mt-2"><%= render article.categories if article.categories.any? %></div>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article, class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article, class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, Updated <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <%= render 'shared/errors', object: @article %>
  <%= form_with(model: @article, class: "shadow mb-2 bg-info rounded", local: true) do |f| %>
    <div class="form-group row p-3">
      <%= f.label :title, class: "col-3 text-light" %><br/>
      <%= f.text_field :title, class: "form-control col-7 shadow mb-3 bg-white rounded", placeholder: "Title of article" %>
    </div>
    <div class="form-group row p-3">
      <%= f.label :description, class: "col-3 text-light" %><br/>
      <%= f.text_area :description, class: "form-control col-7 shadow mb-3 bg-white rounded", rows: 10, placeholder: "Description of article" %>
    </div>
    <div class="form-group row p-3">
      <%= f.label :category, class: "col-3 text-light" %><br/>
      <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Make your selection from the list below(can be empty)" }, { multiple: true, size: 3, class: "form-control col-7 shadow mb-3 bg-white rounded" }) %>
    </div>
    <div class="row">
      <div class="col-4 offset-4">
        <%= f.submit class: "btn btn-lg btn-success w-100 mb-2" %>
      </div>
    </div>
  <% end %>

  <p class="text-center"><%= link_to yield(:articles_listing), articles_path, class: "text-info" %></p>
</div>  

app/views/articles/edit.html.erb
<% provide(:articles_listing, "Cancel and return to articles listing") %>
<h2 class="text-center mt-2">Edit Article</h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing Articles</h1>
<div class="flickr_pagination">
  <%= will_paginate @articles, container: false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, container: false %>
</div>

app/views/articles/new.html.erb
<% provide(:articles_listing, "Return to articles listing") %>
<h2 class="text-center mt-2">Create a new Article</h2>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h1>
<div class="container">
  <div class="row">
    <div class="col-8 offset-sm-2 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username if @article.user.present? %>
          <%= link_to gravatar_for(@article.user), @article.user %>
          <div class="mt-2"><%= render @article.categories %></div>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= 
          simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", @article, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, Updated <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category, class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<div class="container">
  <%= render 'shared/errors', object: @category %>
  <%= form_with(model: @category, class: "shadow mb-2 bg-info rounded", local: true) do |f| %>

    <div class="form-group row p-3">
      <%= f.label :name, "Category name", class: "col-3 text-light" %><br/>
      <%= f.text_field :name, class: "form-control col-7 shadow mb-3 bg-white rounded", placeholder: "Enter a name" %>
    </div>

    <div class="row form-group">
      <div class="col-4 offset-4">
        <%= f.submit class: "btn btn-lg btn-success w-100 mb-2" %>
      </div>
    </div>
  <% end %>
  
  <p class="text-center">
    <% if @category.new_record? %>
      <%= link_to "Return to categories listing", categories_path, class: "text-info" %>
    <% else %>
      <%= link_to "Return to the category", @category %>
    <% end %>
  </p>
</div>  

app/views/categories/edit.html.erb
<h2 class="text-center mt-2">Edit category name</h2>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<div class="flickr_pagination">
  <%= will_paginate @categories, container: false %>
</div>
<div class="container">
  <% @categories.each do |category| %>
    <div class="row">
      <div class="col-4 mt-4 offset-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category, class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "Article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, Updated <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination">
  <%= will_paginate @categories, container: false %>
</div>  

app/views/categories/new.html.erb
<h2 class="text-center mt-2">Create Categories</h2>
<%= render 'form' %>

app/views/categories/show.html.erb
<h2 class="text-center mt-2"><%= @category.name %></h2>
<% if logged_in? && current_user.admin %>
  <div class="text-center mt-4">
    <%= link_to "Edit Category", edit_category_path(@category), class: "btn btn-outline-success" %>
  </div>
<% end %>  
<h2 class="text-center mt-4">Articles</h2>
<div class="flickr_pagination">
  <%= will_paginate @articles, container: false %>
</div>
<%= render 'articles/article' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, container: false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <a href="https://nitish-alpha-blog.herokuapp.com" target= "_blank" class="text-white">Nitish Anand</a></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div> 
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "View Articles", articles_path, class: "dropdown-item" %>
          <%= link_to "Create new article", new_article_path, class: "dropdown-item" if logged_in? %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "View Categories", categories_path, class: "dropdown-item" %>
          <%= link_to "Create new category", new_category_path, class: "dropdown-item" if logged_in? && current_user.admin? %>
        </div>
      </li>      
      
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", current_user, class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", current_user, method: :delete, data: { confirm: "Are you sure?" }, class: "dropdown-item text-danger" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>
<%= link_to "Articles Listing", articles_path %> |
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>  

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= object.class.name.downcase %> from being saved.</h4>
    <ul class="row">
      <% object.errors.full_messages.each do |msg| %>
        <li class="col-8 offset-2"><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <%= render 'shared/errors', object: @user %>
  <%= form_with(model: @user, class: "shadow mb-2 bg-info rounded", local: true) do |f| %>

    <div class="form-group row p-3">
      <%= f.label :username, class: "col-3 text-light" %><br/>
      <%= f.text_field :username, class: "form-control col-7 shadow mb-3 bg-white rounded", placeholder: "Enter a username" %>
    </div>

    <div class="form-group row p-3">
      <%= f.label :email, class: "col-3 text-light" %><br/>
      <%= f.email_field :email, class: "form-control col-7 shadow mb-3 bg-white rounded", placeholder: "Enter your email address" %>
    </div>

    <div class="form-group row p-3">
      <%= f.label :password, class: "col-3 text-light" %><br/>
      <%= f.password_field :password, class: "form-control col-7 shadow mb-3 bg-white rounded", rows: 10, placeholder: "Enter your password" %>
    </div>

    <div class="row form-group">
      <div class="col-4 offset-4">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-lg btn-success w-100 mb-2") %>
      </div>
    </div>
  <% end %>
  
  <p class="text-center"><%= link_to "Cancel and return to articles listing", articles_path, class: "text-info" %></p>
</div>  

app/views/users/edit.html.erb
<h2 class="text-center mt-2">Users Edit Form</h2>
<%= render 'form' %>

app/views/users/index.html.erb
<h2 class="text-center mt-2">Alpha Bloggers</h2>
<div class="flickr_pagination">
  <%= will_paginate @users, container: false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row">
      <div class="col-8 offset-sm-2 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "Article") %></p>
            <div class="mt-3">
              <%= link_to "View Profile", user, class: "btn btn-outline-success" %>
              <% if logged_in? %>
                <% if user == current_user %>
                  <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-outline-info" %>
                <% end %>
                <% if current_user.admin? %>
                  <%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure you want to delete this user?"}, class: "btn btn-outline-danger" %>
                <% end %>  
              <% end %>  
            </div>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago, Updated <%= time_ago_in_words(user.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>  
</div>
<div class="flickr_pagination mb-4">
  <%= will_paginate @users, container: false %>
</div>

app/views/users/new.html.erb
<h2 class="text-center mt-2">Users Signup Form</h2>
<%= render 'form' %>

app/views/users/show.html.erb
<h2 class="text-center mt-2"><%= @user.username %>'s profile</h2>
<%= gravatar_for @user, size: 200 %>
<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-success" %>
  </div>
<% end %>  

<h2 class="text-center mt-4">Articles</h2>
<div class="flickr_pagination">
  <%= will_paginate @articles, container: false %>
</div>
<%= render 'articles/article' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, container: false %>
</div>